schema: "classroom50/repo-config/v1"
classroom: "f215-digital-design"
assignment: "dd-2026-verilog-labs"
owner:
  username: "Rohan-Kapoor19"
  id: 318322115
  accepted_at: "2026-08-28T12:10:34Z"
source:
  owner: "f2152026"
  owner_id: 316136693
  repo: "verilog-labs"
  branch: "main"
